<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Laravel\Sanctum\Sanctum;
use Tests\TestCase;

class UserPreferenceTest extends TestCase
{
    use RefreshDatabase;

    /**
     * Test that unauthenticated users are blocked.
     */
    public function test_unauthenticated_users_cannot_access_preferences(): void
    {
        $response = $this->getJson('/user/preferences');

        if ($response->status() !== 401) {
            $response->dump();
        }

        $response->assertStatus(401);
    }

    /**
     * Test fetching user preferences returns defaults for new users.
     */
    public function test_user_can_retrieve_default_preferences(): void
    {
        $user = User::factory()->create();

        // IMPORTANT: Refresh the model to load the default values generated by the database
        $user->refresh();

        Sanctum::actingAs($user);

        $response = $this->getJson('/user/preferences');

        $response->assertStatus(200)
            ->assertJsonStructure([
                'status',
                'data' => [
                    'target_meals_per_week',
                    'default_portions',      // <-- NEW
                    'dietary_preferences',
                    'fitness_goals',
                    'logistics_preferences',
                    'allergies',             // <-- NEW
                    'minimize_food_waste', 
                ],
            ])
            ->assertJsonPath('data.target_meals_per_week', 3)
            ->assertJsonPath('data.default_portions', 2) // <-- Default value from database
            ->assertJsonPath('data.dietary_preferences', [])
            ->assertJsonPath('data.allergies', [])       // <-- Default empty array
            ->assertJsonPath('data.minimize_food_waste', true);
    }

    /**
     * Test successful update with valid categories.
     */
    public function test_user_can_update_preferences_with_valid_data(): void
    {
        $user = User::factory()->create();

        Sanctum::actingAs($user);

        $payload = [
            'target_meals_per_week' => 5,
            'default_portions' => 4,
            'dietary_preferences' => ['vegan', 'low-carb'],
            'fitness_goals' => ['high-protein'],
            'logistics_preferences' => ['family-friendly'],
            'allergies' => ['nuts', 'soy'],
            'minimize_food_waste' => false, 
        ];

        $response = $this->putJson('/user/preferences', $payload);

        $response->assertStatus(200)
            ->assertJsonPath('status', 'success')
            ->assertJsonPath('data.target_meals_per_week', 5)
            ->assertJsonPath('data.default_portions', 4)
            ->assertJsonPath('data.minimize_food_waste', false); 

        // Verify database was actually updated
        $this->assertDatabaseHas('users', [
            'id' => $user->id,
            'target_meals_per_week' => 5,
            'default_portions' => 4,
            'minimize_food_waste' => 0,
        ]);

        $user->refresh();
        $this->assertEquals(['vegan', 'low-carb'], $user->dietary_preferences);
        $this->assertEquals(['nuts', 'soy'], $user->allergies);
    }

    /**
     * Test validation failure on invalid categories.
     */
    public function test_validation_fails_on_invalid_categories(): void
    {
        $user = User::factory()->create();

        Sanctum::actingAs($user);

        $payload = [
            'target_meals_per_week' => 4,
            'default_portions' => 2,
            'dietary_preferences' => ['carnivore'], 
            'fitness_goals' => ['super-strong'],
            'allergies' => ['dust'],
            'minimize_food_waste' => 'yes-please',
        ];

        $response = $this->putJson('/user/preferences', $payload);

        $response->assertStatus(422)
                 // Tell Laravel to look for the validation errors inside the 'data' key instead of 'errors'
            ->assertJsonValidationErrors(['dietary_preferences.0', 'fitness_goals.0', 'allergies.0', 'minimize_food_waste'], 'data');
    }
}