<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Laravel\Sanctum\Sanctum; // <-- IMPORTANT: Import Sanctum
use Tests\TestCase;

class UserPreferenceTest extends TestCase
{
    use RefreshDatabase;

    /**
     * Test that unauthenticated users are blocked.
     */
    public function test_unauthenticated_users_cannot_access_preferences(): void
    {
        $response = $this->getJson('/user/preferences');

        // Temporary debug output to see what is hiding behind the 404 error
        if ($response->status() !== 401) {
            $response->dump();
        }

        $response->assertStatus(401);
    }

    /**
     * Test fetching user preferences returns defaults for new users.
     */
    public function test_user_can_retrieve_default_preferences(): void
    {
        $user = User::factory()->create();

        // IMPORTANT: Refresh the model to load the default values (like 3) generated by the database
        $user->refresh();

        Sanctum::actingAs($user);

        $response = $this->getJson('/user/preferences');

        $response->assertStatus(200)
            ->assertJsonStructure([
                'status',
                'data' => [
                    'target_meals_per_week',
                    'dietary_preferences',
                    'fitness_goals',
                    'logistics_preferences',
                ],
            ])
            ->assertJsonPath('data.target_meals_per_week', 3)
            ->assertJsonPath('data.dietary_preferences', []);
    }

    /**
     * Test successful update with valid categories.
     */
    public function test_user_can_update_preferences_with_valid_data(): void
    {
        $user = User::factory()->create();

        Sanctum::actingAs($user);

        $payload = [
            'target_meals_per_week' => 5,
            'dietary_preferences' => ['vegan', 'low-carb'],
            'fitness_goals' => ['high-protein'],
            'logistics_preferences' => ['meal-prep-friendly'],
        ];

        $response = $this->putJson('/user/preferences', $payload);

        $response->assertStatus(200)
            ->assertJsonPath('status', 'success')
            ->assertJsonPath('data.target_meals_per_week', 5);

        // Verify database was actually updated
        $this->assertDatabaseHas('users', [
            'id' => $user->id,
            'target_meals_per_week' => 5,
        ]);

        $user->refresh();
        $this->assertEquals(['vegan', 'low-carb'], $user->dietary_preferences);
    }

    /**
     * Test validation failure on invalid categories.
     */
    public function test_validation_fails_on_invalid_categories(): void
    {
        $user = User::factory()->create();

        Sanctum::actingAs($user);

        $payload = [
            'target_meals_per_week' => 4,
            'dietary_preferences' => ['carnivore'], // Not in ALLOWED_DIETS
            'fitness_goals' => ['super-strong'],     // Not in ALLOWED_FITNESS
        ];

        $response = $this->putJson('/user/preferences', $payload);

        $response->assertStatus(422)
            ->assertJsonValidationErrors(['dietary_preferences.0', 'fitness_goals.0'], 'data');
    }
}
